Setup of ODE Solver Script
gr812b/CVT-Simulator pull request #58
Opened 2024-10-30 18:57 UTC by gr812b

**Description**
Initial POC with python script, ODE solver, proper structure, etc
**Changes**
List the main changes made in this PR:
- [X] Initial setup of simplistic ODE solver
- [X] Proper python file structure
- [X] OOP approach on utilizing scipys ODE solver for clear typing

**Additional Notes**
None

2024-11-04 16:10 UTC, t-wing11 approved these changes
Looks good, like the oop implementation for this.

Nice separation of the different aspects, constants, simulations, etc.

Only nitpick would be more consistency, some files have tons of comments and others have none. Not sure what direction we want to go in but probably better to pick one

2024-11-04 16:14 UTC, gr4cem requested changes
variable ENGINE_INTERTIA is misspelled.

2024-11-04 16:22 UTC, gr812b commented
> Only nitpick would be more consistency, some files have tons of comments and others have none. Not sure what direction we want to go in but probably better to pick one

Did you find the comments in say engine_simulation helpful? I'm on the fence as the code looks a lot messier and harder to read but maybe the context (and units) are helpful?

2024-11-04 16:29 UTC, gr4cem approved these changes

2024-11-06 17:25 UTC, t-wing11 approved these changes

2024-11-06 17:56 UTC, merged