Unity Project POC
gr812b/CVT-Simulator pull request #87
Opened 2024-11-07 02:37 UTC by t-wing11

**Description**
Unity project for POC

**Changes**
List the main changes made in this PR:
- [ ] Item 1
- [ ] Item 2
- [ ] Item 3

**Screenshots (if applicable)**
Add screenshots to show the changes (if any).

**Additional Notes**
Any other things of note, could include bugs, new warnings, or other things changed that do not concern the main PR content.

2024-11-09 22:31 UTC, camdnnn requested changes
I think that the folder structure should be changed. I think that it would make more sense to keep the frontend and backend separate instead of having the frontend folder within the backend structure.

Also, I think that we should look into how we can reduce the amount of files being committed here especially meta and packages

2024-11-11 18:21 UTC, gr812b requested changes
Need to fix version control with assets and whatnot

2024-11-12 03:46 UTC, t-wing11 commented
@camdnnn 

We should create a PR to combine the backend folders into a "backend" folder. That way we will have frontend and backend together.

Also fixed the PR, down to 57 files and 7k lines

2024-11-13 16:40 UTC, gr812b approved these changes

2024-11-13 17:12 UTC, camdnnn approved these changes

2024-11-13 17:15 UTC, merged